version: '3'
services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=111111
      - MYSQL_DATABASE=hoctienganh
    volumes:
      - /mysql-volume:/var/lib/mysql 

  backend:
    build:
      context: ./../backend_el_2025
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=111111
      - MYSQL_DATABASE=hoctienganh
      - MYSQL_HOST=db
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=2048
    ports:
      - '9000:9000'
volumes:
  mysql-volume:
    driver: local
